# Generated by Django 5.0.14 on 2025-10-14 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zookeeper', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='animal',
            name='last_fed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='species',
            name='diet',
            field=models.CharField(choices=[('herbivore', 'Herbivore'), ('carnivore', 'Carnivore'), ('omnivore', 'Omnivore')], max_length=20),
        ),
        migrations.AlterField(
            model_name='species',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
