# Generated by Django 5.2.6 on 2025-11-01 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zookeeper', '0003_enclosure_alter_species_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='animal',
            name='enclosure',
            field=models.CharField(max_length=100),
        ),
    ]
