# Generated by Django 5.2.6 on 2025-11-01 13:28

import django.db.models.deletion
from django.db import migrations, models


def _map_enclosure_strings_to_ids(apps, schema_editor):
    """
    Map existing Animal.enclosure string values to the corresponding
    Enclosure PKs by replacing the text with the enclosure id (as string).
    This prepares the column for being altered from CharField to FK.
    """
    Animal = apps.get_model('zookeeper', 'Animal')
    Enclosure = apps.get_model('zookeeper', 'Enclosure')

    for animal in Animal.objects.all():
        name = animal.enclosure
        if not name:
            continue
        try:
            enc = Enclosure.objects.get(name=name)
        except Enclosure.DoesNotExist:
            enc = Enclosure.objects.create(name=name, diet_type='omnivore', capacity=3, description=f'Auto-created from migration for {name}')
        # update the charfield value to the enclosure id (string) so the subsequent
        # AlterField to FK will find matching integer ids
        Animal.objects.filter(pk=animal.pk).update(enclosure=str(enc.pk))


def _noop_reverse(apps, schema_editor):
    # No-op reverse; rolling back this mapping isn't straightforward.
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('zookeeper', '0005_create_enclosures'),
    ]

    operations = [
        migrations.RunPython(_map_enclosure_strings_to_ids, _noop_reverse),
        migrations.AlterField(
            model_name='animal',
            name='enclosure',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='zookeeper.enclosure'),
        ),
    ]
