# Generated by Django 5.2.6 on 2025-11-01 13:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('zookeeper', '0006_alter_animal_enclosure'),
        ('zookeeper', '0007_create_enclosures'),
    ]

    operations = [
    ]
