# Generated by Django 5.0.14 on 2025-11-10 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zookeeper', '0008_merge_20251101_1535'),
    ]

    operations = [
        migrations.AddField(
            model_name='enclosure',
            name='last_cleaned_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
