# Generated by Django 5.2.6 on 2025-11-11 12:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zookeeper', '0009_enclosure_last_cleaned_at'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StaffRole',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('manager', 'Manager'), ('keeper', 'Keeper'), ('monitor', 'Monitor')], default='monitor', max_length=20)),
                ('assigned_at', models.DateTimeField(auto_now_add=True)),
                ('assigned_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='staff_assignments_made', to=settings.AUTH_USER_MODEL)),
                ('enclosure', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='staff_assignments', to='zookeeper.enclosure')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='staff_roles', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Staff Roles',
                'ordering': ['enclosure', 'role'],
                'unique_together': {('user', 'enclosure')},
            },
        ),
    ]
